### ISSUE TITLE
Create and share slides for sections 1 and 4 of the Demo

### ISSUE THREAD

**Issue by AndresZarta** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#10]
Sprint Goal and Outcomes

**Comment by Anotherlynn** [comment]
Here is the place for the shared slides in progress: [SprintDemo1](https://docs.google.com/presentation/d/1c04Kgu-jBlZJcKgwFvbxH1MgJ79Bi8My-EzwMt11zCU/edit?usp=sharing)
