### ISSUE TITLE
Chat with partner after finishing the game

### ISSUE THREAD

**Issue by ll4407** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#17]
As a user that has finished the game I want to chat with my partner so that we can get to know one another more.

**Comment by peng-qi-ben** [comment]
Once the role-playing game is concluded, users transition into a chat window, allowing them to have deeper, unrestricted conversations with their match and reference past game interactions.

**Comment by peng-qi-ben** [comment]
After interactions or games, users can provide feedback on their experiences, report any inappropriate behavior, and expect that their feedback is confidential and leads to appropriate actions for reported behavior.
