### ISSUE TITLE
As a user, I want the option to share my personal moon signs interpretation for a given moon sign on each night that matches a moon phase, so that I can refine my reactions to be more accurate over time.

### ISSUE THREAD

**Issue by AndresZarta** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#185]
**User Story**
As a user, I want the option to share my personal moon signs interpretation for a given moon sign on each night that matches a moon phase, so that I can refine my reactions to be more accurate over time.

**Acceptance Criteria:**
- [x] On nights that correspond with a moon phase, the user is prompted to share their personal moon signs interpretation using the word pool
- [x]  Users are provided with an interface that pre-populates their existing interpretations.
- [x]  User is able to reselect their choice for ambiguous moon signs. 
- [x]  Changes to interpretations are saved immediately and are reflected the next time moon signs are used as reactions in the game.

**Definition of Done:**
- [x]  The moon phase feature has been implemented and integrated into the night sequence.
- [x]  The feature has been manually tested to ensure it meets the acceptance criteria.
- [x]  Automated tests have been written, passed, and provide sufficient coverage for the new functionality.
- [x]  The updated feature has been reviewed, approved, and merged into the main codebase without causing disruptions.
- [x]  The feature has been deployed to the production environment and is being monitored for performance and user feedback.

**Comment by Anotherlynn** [comment]
[problem of connecting websocket, "submit" isn't working]

**Comment by aya0221** [comment]
> [problem of connecting websocket, "submit" isn't working]

It has been fixed, and a pull request has been made to the develop from BugFix_Team branch! ([#304](https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-5/pull/304))
