### ISSUE TITLE
As user, I want the game turn sequence to take place live between 9 to 10 pm EST, so that I can have an immersive, live roleplay experience in real-time.

### ISSUE THREAD

**Issue by AndresZarta** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#199]
**Acceptance Criteria:**
- [ ]  The game sequence is programmed to only be live during the specified hours of 9 to 10 pm EST.
- [ ]  A system check ensures that the user’s local time is correctly syncing with EST to enable participation at the correct hours.
- [ ]  The system gracefully handles the end of the live session at 10 pm EST, providing users with a clear indication that the live period has ended.

**Definition of Done**
- [ ]  Implementation of the live turn sequence between the specific hours has been completed.
- [ ]  Automated tests verify the live session timing.
- [ ]  The feature has passed code review.
- [ ]  The new feature has been merged into the main branch after passing all tests.
- [ ]  The feature has been deployed to the production environment and verified by users during actual live sessions.

**Comment by Anotherlynn** [comment]
alternative solution: 9PM release new turn and user can finish the turn by anything before tomorrows' 9PM.
