### ISSUE TITLE
When a logged in user ends the game, but the second user is not logged in or is not notified of the change to navigate to the end url the game doesn’t end. 

### ISSUE THREAD

**Issue by AndresZarta** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#243]
When a logged in user ends the game, but the second user is not logged in or is not notified of the change to navigate to the end url, the game doesn’t end completely for the first user. 

This is due to the way the end_game logic is implemented, requiring one player to end the game, the other to confirm. We can change that logic, but I also think it would be beneficial to rethink how we check for the existence of a game session: (Should it be about its absence in the database or its state being "Inactive" or "Ended".

**Comment by aya0221** [comment]
- keep the game database for certain period of time after the game has been deleted
- game: organize/clean
- uni-test
