### ISSUE TITLE
No reaction for selected answers

### ISSUE THREAD

**Issue by SoyMark** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#248]
I clicked the one of the choices, but nothing that made me confirm what I just selected happened
<img width="1034" alt="test_team5_2" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-5/assets/65658776/283c3a54-8861-4409-9c96-baeb874aaeb5">

**Comment by AndresZarta** [comment]
Hi! The intent is to drag and drop on the answer box. You raise a very valid point that this inteded behavior might not be obvious to the user.

**Comment by AndresZarta** [comment]
Team 5: This has been added to user story #262
