### ISSUE TITLE
Allows blank answers

### ISSUE THREAD

**Issue by xxzz-tt** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#250]
Not sure if it's intended but the game currently allows players to submit a reply without any answers. Also, not quite sure what the emojis are supposed to mean, perhaps it would be helpful to give a one-liner explanation of that 

<img width="945" alt="Screenshot 2023-11-17 at 3 33 30 PM" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-5/assets/59352954/3b2d49fd-5de4-42e5-8240-bea2f5a3b534">
<img width="949" alt="Screenshot 2023-11-17 at 3 36 56 PM" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-5/assets/59352954/610f4fbf-bd73-4615-8863-44bb8d28c4b7">

**Comment by AndresZarta** [comment]
Thank you!

Team 5: This is a suggestion to add tutorial snippets for the game sequence
