### ISSUE TITLE
When i submit a question without selecting a question it breaks the socket connection

### ISSUE THREAD

**Issue by jayjayh** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#251]
The video is a bit too long but some questions will close the connection and some other questions can handle it well enough

https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-5/assets/26288542/6b46c691-f4f5-4b02-bf26-60653c5efbb2

**Comment by AndresZarta** [comment]
This is a great bug you identified! Thank you!
