### ISSUE TITLE
As a user, I want to be able to upload pictures to create a visual profile.

### ISSUE THREAD

**Issue by AndresZarta** [gcivil-nyu-org/INET-Monday-Fall2023-Team-5#27]
**User story**
As a user, I want to be able to upload pictures to my profile so that prospective matches can see if there is physical attraction.

**Acceptance criteria**
- Users should have an "Upload Pictures" section within their profile dashboard.
- Users can select one or multiple images from their device to upload.
- Supported file formats are: JPEG, PNG.
- Each user should have a defined maximum number of pictures they can upload (e.g., 5).
- Uploaded pictures should be displayed in a user-friendly gallery format.
- Users can delete or replace pictures they previously uploaded.
- Picture resolution and size should meet defined requirements to ensure fast load times and optimal display.
- Pictures should be screened or reviewed for appropriateness (no nudity, violence, or copyrighted content).
- There should be an option to set one of the uploaded pictures as the "profile picture".

**Definition of Done**

- All acceptance criteria have been satisfied.
- The picture upload feature has been manually tested across multiple devices and browsers.
- Uploaded pictures are securely stored, and privacy concerns are addressed.
- Automated tests related to the picture upload feature have been written and pass successfully.
- The code for this feature has been reviewed by a fellow team member.
- The feature has been deployed to a staging environment, and no critical issues have been identified.
- Performance benchmarks for picture loading times are within acceptable ranges.

**Comment by Anotherlynn** [comment]
https://learndjango.com/tutorials/django-file-and-image-uploads-tutorial
